[package]
name = "rdb"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
copperline = "0.3.0"
iced-x86 = "1.21.0"
memmap2 = "0.9.5"
nix = { version = "0.30.1", features = ["ptrace", "fs", "signal"] }
rustc-demangle = "0.1.25"
sysnames = "0.1.3"
