[package]
name = "rdb"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
copperline = "0.3.0"
iced-x86 = "1.21.0"
nix = { version = "0.29.0", features = ["ptrace", "fs", "signal"] }
sysnames = "0.1.3"
